# Generated by Django 2.2.4 on 2019-08-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogood_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='org_id',
            new_name='org_name',
        ),
    ]
