# Generated by Django 2.2.4 on 2019-08-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogood_app', '0004_auto_20190815_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='org_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dogood_app.Organization'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='volunteers', to='dogood_app.Event'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
